### ISSUE TITLE
Make report printable

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-National#80]
Allow the user to print Report content.

**Comment by ltmetz** [comment]
@mitchas, and others, I added the workflow outputs to the print modal as discussed during our check-in yesterday. Mitch, the format is currently the same as the report popout, and the window.print() method is printing the entire modal. Let me know if there is anything you need from me, otherwise I believe we just need your amazing skillz to complete this issue. Thank you, Mitch!

**Comment by amedenblik** [comment]
Closed with #147
